### PR TITLE
callable listeners signature requires Payload type, not the Payload's content

### PR DESCRIPTION
**Pull request by MatteoOreficeIT**
Hi @WyriHaximus , it is a small fix but I cannot run anymore my project without fixing it

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Hey @MatteoOreficeIT thanks for this. A few quick things tho. Which PHP version is this on? The master branch is currently in a state of being prepared and for a new major release that supports PHP 7.4+ and of course PHP 8. Are you using a tagged version or `dev-master`?

**Comment by MatteoOreficeIT** [comment]
Hi @WyriHaximus , thanks to you, it is an useful project, we were using in our projects the tagged version v2.10.0 , but we noticed exceptions with additional parameters are not right serialized between messenger parent and child process so the last week we looked in master if an improvement had been released in the meantime, and it was there! 

We forked from c27fc13ff6a8b53318121661d3038ea5499f452f , but a bug didn't allow to run our code anymore after we integrated `AdditionalPropertiesInterface`, so we made the previous fix on a bugfix, our intent was try to run the code with the improvement quicky, due project's time requirements

```txt

* commit af13d19c03ded07894037d5a1bcd89405b653354 (HEAD -> bugfix, origin/bugfix)
| Author: Matteo Orefice <matteo.orefice@bitia.it>
| Date:   Fri Feb 12 17:15:58 2021 +0100
|
|     Add target name to exception
|
* commit 5e7cc72654a115aeb0ffa7c39b93a3c60016f438
| Author: Matteo Orefice <matteo.orefice@bitia.it>
| Date:   Thu Feb 11 11:18:37 2021 +0100
|
|     fix: callable listeners require type Payload, not the Payload content
|
*   commit 260a62c0bedfe2c560947794b8232d1b2cd1e287 (origin/master, origin/HEAD, master)
|\  Merge: c27fc13 3c253c4
| | Author: Cees-Jan Kiewiet <ceesjank@gmail.com>
| | Date:   Mon Feb 8 13:03:44 2021 +0100
| |
| |     Merge pull request #44 from WyriHaximus/dependabot/composer/cakephp/utility-4.2.3
| |
| |     Bump cakephp/utility from 3.9.6 to 4.2.3
| |
| * commit 3c253c477d4cd84c33f459a9556cb4058e86ae45
|/  Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
|   Date:   Sun Feb 7 21:15:20 2021 +0000
*   commit c27fc13ff6a8b53318121661d3038ea5499f452f

```

**Comment by WyriHaximus** [comment]
Ok hold on, let me create the `v2.10.x` branch so we can get `v2.10.1` out with this fix for you.

**Comment by WyriHaximus** [comment]
Ok create the branch, and changed the target branch for this PR to that branch. Could you rebase?

**Comment by MatteoOreficeIT** [comment]
Hi @WyriHaximus , sorry for the late answer, I tried to rebase my two commits onto 2.10.x branch,  but noted the issue was introduced by the commit c27fc13f  after the commit actually pointed by branch 2.10.x ( 0aff0955  ) but before my bugfix branch fork-point ( 260a62c0 )

So rebasing onto 2.10.x is irrevelevant because the issue was not introduced yet

Thanks

**Comment by WyriHaximus** [comment]
Ahhh doh sorry my bad @MatteoOreficeIT, I've also started working on modernizing the code base in #47 and this fix might also have slipped into that branch as I've been going over all unit tests to make sure all of them pass. Let me change the target for this PR back to master and merge it if it passes :+1:

**Pull request merged**
