### PR TITLE
Allow thecodingmachine/safe 2

### PR DESCRIPTION
**Pull request by holtkamp**
To prevent a lot of deprecation messages when running version 1 on PHP 8.4

### CODE REVIEW

**Review by WyriHaximus — CHANGES_REQUESTED** [review]
Need to review how best to move away from safe anyway in the long term. But for now can you also made sure `composer.lock` is updated with `composer update --lock`?

**Comment by holtkamp** [comment]
Aah, yeah, ofcourse, did not see the `composer.lock` was included. 

Tried to amend my last commit, feel free to squash commits to prevent GIT history pollution...

**Review by WyriHaximus — APPROVED** [review]

**Comment by holtkamp** [comment]
@WyriHaximus thanks! Can this also be tagged as a release in the version 4 branch? I suppose 4.0.4?

This library depends on it: https://github.com/WyriHaximus/reactphp-child-process-pool/blob/1ad9bc8c00e2dbebdd9559f57175b6f8eb86ce27/composer.json#L17

Which is used by: https://github.com/reactphp/filesystem/blob/766cdef9ba806367114f0c5ba36ea2a6eec8ccd2/composer.json#L19

;)

**Comment by WyriHaximus** [comment]
> @WyriHaximus thanks! Can this also be tagged as a release in the version 4 branch? I suppose 4.0.4?

Not on this branch, this is for the upcoming v5. Could you create a PR for the 4.x branch so I can get a new v4 version out the door?

**Comment by holtkamp** [comment]
Sure, see [#143](https://github.com/WyriHaximus/reactphp-child-process-messenger/pull/143)

**Comment by holtkamp** [comment]
@WyriHaximus you wrote: 

>Need to review how best to move away from safe anyway in the long term. 

Both `json_encode()` and `json_decode()` now allow a flag to throw exceptions, that might be useful to start with. 

This might be an interesting discussion though: https://github.com/thecodingmachine/safe/issues/437

Then the following functions that use the Safe dependency remain (scanned quickly):

- Safe\base64_decode() in:
-- WyriHaximus\React\ChildProcess\Messenger\ChildProcess\ArgvEncoder
-- WyriHaximus\React\ChildProcess\Messenger\Messages
- Safe\scandir() in WyriHaximus\FileDescriptors\ScanDir
- Safe\sprintf() in WyriHaximus\React\ChildProcess\Messenger\Factory

**Pull request merged**
